FROM            eb_ubuntu
MAINTAINER      poopa8788@gmail.com

# 현재경로의 모든 파일들을 컨테이너의 /srv/deploy_eb_docker 폴더에 복사
COPY            . /srv/deploy_eb_docker

WORKDIR         /srv/deploy_eb_docker
RUN             /root/.pyenv/versions/deploy_eb_docker/bin/pip install -r .requirements/debug.txt

EXPOSE          80 8000

# 실행
#docker -run --rm -it -p 9000:8000 eb /bin/zsh